#include "hid_gamecube_mapping.h"

/*
PS4 DualShock 4 
HID report buttons mapping:
Button 0x01 - Square button
Button 0x02 - Cross button
Button 0x03 - Circle button
Button 0x04 - Triangle button
Button 0x05 - L1 button
Button 0x06 - R1 button
Button 0x07 - L2 button
Button 0x08 - R2 button
Button 0x09 - Share button
Button 0x0A - Options button
Button 0x0B - L3 button
Button 0x0C - R3 button
Button 0x0D - PS button
Button 0x0E - Touchpad button

PS5 DualSense HID report buttons mapping:
Button 0x01 - Square button
Button 0x02 - Cross button
Button 0x03 - Circle button
Button 0x04 - Triangle button
Button 0x05 - L1 button
Button 0x06 - R1 button
Button 0x07 - L2 button
Button 0x08 - R2 button
Button 0x09 - Create button
Button 0x0A - Options button
Button 0x0B - L3 button
Button 0x0C - R3 button
Button 0x0D - PS button
Button 0x0E - Touchpad button
Button 0x0F - Mute button
*/

JoyPreset hid_to_gamecube_mapping[] =
{
	// Pad Number, Input Usage Page, Input Usage, Output Channel, Output Control, InputType, Input Param
	// Buttons
	{ 1, REPORT_USAGE_PAGE_BUTTON, 1, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_Y, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // Square -> Y
	{ 1, REPORT_USAGE_PAGE_BUTTON, 2, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_A, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // Cross -> A
	{ 1, REPORT_USAGE_PAGE_BUTTON, 3, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_B, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // Circle -> B
	{ 1, REPORT_USAGE_PAGE_BUTTON, 4, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_X, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // Triangle -> X

//	{ 1, REPORT_USAGE_PAGE_BUTTON, 5, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_?, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // L1
	{ 1, REPORT_USAGE_PAGE_BUTTON, 6, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_Z, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // R1

	// Note: DualShock S4 generates press event starting from minimum force,
	// GameCube controller generates L/R clicks after maximum force to analog L/R axes applied.
	// Can be replaced with mapping analog Rx/Ry axis with MAP_TYPE_THRESHOLD_ABOVE 192 (75%) to GameCube L/R.
	{ 1, REPORT_USAGE_PAGE_BUTTON, 7, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_L, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // L2 Digital
	{ 1, REPORT_USAGE_PAGE_BUTTON, 8, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_R, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // R2 Digital

	{ 1, REPORT_USAGE_PAGE_BUTTON, 10, MAP_GAMEPAD, MAP_GAMECUBE_BUTTON_START, MAP_TYPE_THRESHOLD_ABOVE, 0 }, // Options -> Start

	// Left analog
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_X, MAP_GAMEPAD, MAP_GAMECUBE_AXIS_X, MAP_TYPE_AXIS, VALUE_TYPE_UINT8 }, // DS_LX
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_Y, MAP_GAMEPAD, MAP_GAMECUBE_AXIS_Y, MAP_TYPE_AXIS, VALUE_TYPE_UINT8 }, // DS_LY
	// Right analog
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_Z, MAP_GAMEPAD, MAP_GAMECUBE_AXIS_CX, MAP_TYPE_AXIS, VALUE_TYPE_UINT8 }, // DS_RX
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_Rz, MAP_GAMEPAD, MAP_GAMECUBE_AXIS_CY, MAP_TYPE_AXIS, VALUE_TYPE_UINT8 }, // DS_RY
	// Analog left/right triggers
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_Rx, MAP_GAMEPAD, MAP_GAMECUBE_AXIS_L, MAP_TYPE_AXIS, VALUE_TYPE_UINT8 }, // DS_LT
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_Ry, MAP_GAMEPAD, MAP_GAMECUBE_AXIS_R, MAP_TYPE_AXIS, VALUE_TYPE_UINT8 }, // DS_RT

	// POV/HAT switch (also D-PAD in most cases)
	// 0 on hat switch, just press up
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_U, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_UP },
	// 1 on hat switch, press up and right
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_U, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_UP_RIGHT },
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_R, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_UP_RIGHT },
	// 2 on hat switch, press right
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_R, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_RIGHT },
	// 3 on hat, press right and down
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_R, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_DOWN_RIGHT },
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_D, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_DOWN_RIGHT },
	// 4 on hat, press down
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_D, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_DOWN },
	// 5 on hat, press down and left
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_D, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_DOWN_LEFT },
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_L, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_DOWN_LEFT },
	// 6 on hat, press left
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_L, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_LEFT },
	// 7 on hat, press left and up
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_L, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_UP_LEFT },
	{ 1, REPORT_USAGE_PAGE_GENERIC_DESKTOP, REPORT_USAGE_HATSWITCH, MAP_GAMEPAD, MAP_GAMECUBE_U, MAP_TYPE_EQUAL, HID_GAMEPAD_HAT_UP_LEFT },

	// Rarely used
	{ 1, REPORT_USAGE_PAGE_BUTTON, REPORT_USAGE_DPAD_UP, MAP_GAMEPAD, MAP_GAMECUBE_U, MAP_TYPE_THRESHOLD_ABOVE, 0 },
	{ 1, REPORT_USAGE_PAGE_BUTTON, REPORT_USAGE_DPAD_DOWN, MAP_GAMEPAD, MAP_GAMECUBE_D, MAP_TYPE_THRESHOLD_ABOVE, 0 },
	{ 1, REPORT_USAGE_PAGE_BUTTON, REPORT_USAGE_DPAD_RIGHT, MAP_GAMEPAD, MAP_GAMECUBE_R, MAP_TYPE_THRESHOLD_ABOVE, 0 },
	{ 1, REPORT_USAGE_PAGE_BUTTON, REPORT_USAGE_DPAD_LEFT, MAP_GAMEPAD, MAP_GAMECUBE_L, MAP_TYPE_THRESHOLD_ABOVE, 0 },

	// null record to mark end
	{ 0, 0, 0, 0, 0, 0, 0 }
};
