#pragma once

#include "hid_parser.h"

enum GamecubeMappings : uint8_t
{
	MAP_GAMECUBE_BUTTON_A,
	MAP_GAMECUBE_BUTTON_B,
	MAP_GAMECUBE_BUTTON_X,
	MAP_GAMECUBE_BUTTON_Y,
	MAP_GAMECUBE_BUTTON_START,
	MAP_GAMECUBE_R,
	MAP_GAMECUBE_L,
	MAP_GAMECUBE_D,
	MAP_GAMECUBE_U,
	MAP_GAMECUBE_BUTTON_Z,
	MAP_GAMECUBE_BUTTON_R,
	MAP_GAMECUBE_BUTTON_L,
	MAP_GAMECUBE_AXIS_X,
	MAP_GAMECUBE_AXIS_Y,
	MAP_GAMECUBE_AXIS_CX,
	MAP_GAMECUBE_AXIS_CY,
	MAP_GAMECUBE_AXIS_L,
	MAP_GAMECUBE_AXIS_R
};

extern JoyPreset hid_to_gamecube_mapping[];